<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class fcmain extends Model
{
    use HasFactory;
    protected $fillable = ['APPL_NO','APDT','FCDATE','AMEND_NO','AMEND_TYPE','COMPANY'.'COMADR1','COMADR2','COMADR3','COMADR4','COMADR5',
    'TELE','TELEX','FAX','CABLE','PLACE','TEHSIL','COLLOB','COLADR1','COLADR2','COLADR3','COLADR4','COLADR5','SCHCODE','SCHCODE_OLD','ITEMNAME',
    'CAPACITY','UNIT','COLTYPE','EQUITY','PEQT','PR_PER_EQ','NRI','PNRI','PREF_SHARE','PREF_PER','EROL','EROL_P','IROL','IROL_P','ROY_TAX',
    'LUMP_TAX','ROYALTY','DATEISSU','ISSUBY','HOLDING','SUBSIDY','STDT','ITEM_CODE','GP_CODE','SEC_TYPE','APRNO','ECNO','ECDATE','ITEMNO','
    INEQ_FLAG','FLAG','EXTRA','COUNCODE','NRI_CNT','AN3','IC','EP','FEP','FEC','IS','SSI','MOD_SEC','PEROB','DUROB','AMTEXOB','INFRASTRU',
    'CONSUMER','TRADE_MANF','MANF_COND','IMPL_STAT1','IMPSTAT_DT','RSN_INEQ_1','RSN_INEQ_2','ADM_NEW','BAL_DIV','TFEE_CURR','TFEE_AMT','TFEE_NO',
    'DD_CURR','DD_AMT','DD_NO','ENG_CURR','ENG_AMT','ENG_NO','PAT_CURR','PAT_AMT','PAT_NO','OTH_AMT','OTH_CURR','OTH_NO','RBIREGNO','RBIREGDT',
    'EXPAND','PR_EQT_AMT','PR_NRI_AMT','PR_PREF_AM','NT_EQT_AMT','NT_NRI_AMT','NT_PREF_AM','PR_PER_NRI','PR_PR_PREF','NEW_STDT','ACQ_INFO',
    'IFLAG','SFLAG'
    ];
    protected $table ='fcmain';
    protected $primarykey ='';
}
